# Generated by Django 4.2 on 2026-05-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consultantavailability',
            index=models.Index(fields=['day_of_week', 'is_available'], name='consultatio_day_of__39654b_idx'),
        ),
    ]
