# Generated by Django 4.2 on 2026-05-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0003_consultantpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantavailability',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='max_bookings_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='consultationsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Approval'), ('confirmed', 'Confirmed'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('payment_released', 'Payment Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date', models.DateField()),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('counter', 'Counter Proposed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests_made', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='consultations.consultationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantSessionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('call', 'Phone Call'), ('video', 'Video Call'), ('email', 'Email'), ('in_person', 'In Person')], max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_type'],
                'unique_together': {('consultant', 'session_type')},
            },
        ),
    ]
