# Generated by Django 4.2 on 2026-04-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_user_portfolio_url_experience_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('consultant', 'Consultant'), ('admin', 'Admin')], default='freelancer', max_length=20),
        ),
    ]
