# Generated by Django 4.2 on 2026-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
