# Generated by Django 4.2 on 2026-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_document_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
