# Generated by Django 4.2 on 2026-05-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_kyc_document_number_user_kyc_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='users_skill_name_0b8e75_idx'),
        ),
        migrations.AddField(
            model_name='expertisetag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expertisetag',
            index=models.Index(fields=['tag'], name='users_exper_tag_51049c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expertisetag',
            unique_together={('user', 'tag')},
        ),
    ]
