# Generated by Django 4.2 on 2026-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_expertisetag_user_is_online_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('consultant', 'Consultant'), ('both', 'Both (Freelancer + Consultant)'), ('admin', 'Admin')], default='freelancer', max_length=20),
        ),
    ]
