# Generated by Django 4.2 on 2026-05-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('proposal_accepted', 'Proposal Accepted'), ('proposal_received', 'Proposal Received'), ('session_booked', 'Session Booked'), ('session_confirmed', 'Session Confirmed'), ('session_cancelled', 'Session Cancelled'), ('session_completed', 'Session Completed'), ('review_received', 'Review Received'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('job_application', 'Job Application'), ('payment_success', 'Payment Success'), ('payment_released', 'Payment Released'), ('reschedule_requested', 'Reschedule Requested'), ('reschedule_responded', 'Reschedule Responded'), ('session_reminder', 'Session Reminder'), ('double_booking_conflict', 'Double Booking Conflict'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
