# Generated by Django 4.2 on 2026-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
